language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - GRADLE_OPTS="-Xmx2048m -Xms2048m -XX:MaxPermSize=1024m"
    - secure: ggHcSlCCGTE/zzm3rifgDvcMb0aujDjxlswOh5pOHRNJ5llig5IXXZ8hhUJAHdjE/syA4NkQNDbv/VW4D79kbkvhxbp/a3atHYAHL/16OnMbjK3JDitKlKAImhlEmIJZBbFmnTYa+Nbzla/CuF7MCX6vWlEnlm9h2UU0XZVM8oCABCiRRpl3286gMYA4MzFxbNimuKltyJ/sIjOlLv+DtsCjsnHsu0soUc/cqHerEDa5WytyI2PFFkwsshQwUUO1A9+kB9EGzzN0zK+WQuFxw0quAlSlmTA9F+sLOy2DXHbDAspm/DNSPdjNjMy1kHjxLkJGmJGKJ5AZJ7I0nQZ626D6UYIfGcv13FGIhl773zZj2Vw4hpAbtiTxOCInre6ULKfA6xnj4q+ohldD/2dMcCRmjL2HnQwfOgiTMs1Wj1nvYb5rAQzKu1Gab5sv7pT+MeFQNqSerWdkUHZuZiTYdZXhqQofXdRitmzPWl4lpvtTuipyjBVzCiPxcSjtvSlx3v6nCiVB1L3TvGPnlF3IkMn5/czU21O1Plkq5g7ZdmvSjuzlB3wKZH0MmQ5RA8v/JgvDFuY+MiaTXsPr/P9PQTKeh32sRjofnqkkQNGh+MLDH9iFSBd4j57a+wPff5lVY6o2kXkTFtq/be5T3PACcn7K8CCHoGz0aFYKZKdqF9o=
    - secure: Hnbjoor3G6gZor+LNLV4DICufZqcurY01EAxmYmIKzIjK9pC2TE9aYTCwmOVO7S7I/0fqxPaIycozmTloB4+sajJ7uQPTuotBHbvoCRl/nbABjl9ECiE3nkCSVGOW8hSL8U1ttYc9fh7wQqVQY3XUer2dxjjTl3irOtmK0Rri2F9IXXKCuX6MskYz42iIlxkmfux5ykn0m6eOSqgKDqbYzRmyKEKL5EW1gOqsFIH0ghk6Vl7cmdl6MGVQOUr3IfZwhLg1+lUVtfA7N+2uCxFZ0b5v6Z6C++M8O70M8Hr7hmVSGRjrzfh7zGqgSB33h9j58LeV2r031FUU2qPQaQ+OWRMwc04K8tPVDTHyoJWoZBsnehCbs2husQa/tEXhD1s7QFvs5ipMP9zgjfHc8DiBdYFQN2wEtlvVJ5tFWL4faSdt14mTyj053zTXkxohrd9oFVXnn8y2ywqyrFZ3ddD+KdUkLxXojjv0v5/SV85KMod+/ElYb0MBxtKFlH+kdh/Jg+EmYUu6ua0vCmj2R1aZsk5L+MdlUgTXk+Q8S2NpHUMlNJQL0Xequ0agQ0MgbtR8vaOE17Pd7bOIDPNRvgrksKS/hOyRv3cSB33OxT/g1JO8Dq04fEFT8tiZUlCmarcu/1w/BfS/8lXOm3et1wu++Ndi3RFHyasj3kgYUnjyUk=
git:
  depth: 9999999
rvm:
  - 2.0.0
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-x86-android-21
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_e4c2a0ebb3c4_key -iv $encrypted_e4c2a0ebb3c4_iv -in helloworld.jks.enc -out helloworld.jks -d
before_script:
  - echo no | android create avd --force -n test -t android-21  --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - make setup
script:
  - ./gradlew connectedAndroidTest
after_success:
  - if [ ${TRAVIS_BRANCH} = master ] && [ ${TRAVIS_PULL_REQUEST} = false ]; then make deploy; fi
notifications:
  email: false
