language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - GRADLE_OPTS="-Xmx2048m -Xms2048m -XX:MaxPermSize=1024m"
    - secure: "gaLJOa0RVI3W6kzppGlCNl15oTOhd8vPcGQ/Xon/kCZJnl5SGncFkYWyFEr9IIWs7A4PINbjVbUIQ+HiDxuFlC0N+7itEPAqlMfW+acrMixly8+8qDiYBDGOlSCVb+jzpmoGHbkUcP+xAIMAqtPhAOfLGIVmDxn+LnALwy3tGtaSDNfg3ImKr6pMW0NlWvP7TFALLEntMxdDNoLGob4rXm7Cja5V1X5SXrywnpf2cihLnMjYsb/KWy2+CYVqX6SeFlnu31N/75BxgIkranf9ZhEfT8wg53tIGgORTpJwEU+zJtiRIhgjjntgNEguPx/GlWkoDL8MpAAyD8U2cMhVp9Q7EzhwzXrZXZBXdt3eYGRj9dJJj96CIxysm4U1HB/BQarAyx0cfi7IKfG+BModf8/h6FjqjyBY6/nuwvUyCQy00DtLfXUMNIOR1LLyWJwiOK7pve/q7fmliiaYBRgK7UqkadFpvmqmejc19NGMtuajZKS5xwliSuLuTfVsblPBPDpga4TzmblJ6ZXpuix+gEHebA2GA2C1DZQR3r+cs5q3T47k69LN96HHJWIhuWSUt5ESRFMQUzwBBzuEwsQhXKAYjJViIQ3DC5+MnHjF7KxzCJgf/JLHWTpDGKYcySjJwZNdhStd6A1s8D8rNaxy6VQ30Vj83g/r/Md8WEPinQo="
git:
  depth: 9999999
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-x86-android-21
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_e4c2a0ebb3c4_key -iv $encrypted_e4c2a0ebb3c4_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - rvm install 2.0.0
before_script:
  - echo no | android create avd --force -n test -t android-21  --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - make setup
script:
  - ./gradlew connectedAndroidTest
after_success:
  - if [ ${TRAVIS_BRANCH} = master ] && [ ${TRAVIS_PULL_REQUEST} = false ]; then make deploy; fi
notifications:
  email: false
